[package]
name = "main"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-files = "0.6.2"
actix-web = "4"
lazy_static = "1.4"
tera = "1"
serde = { version = "1.0.152", features = ["derive"] }
